### ISSUE TITLE
Forgot Password Fails If Invalid Email Address Is Entered

### ISSUE THREAD

**Issue by xnodeoncode** [kahanu/Security-Guard#11]
When completing forgot password. If the user enters an unregistered email address then the application errors. The ForgotPassword action should do something like this:

```
        [HttpPost]
        public ActionResult ForgotPassword(ForgotPasswordViewModel model) {

                  // Get the userName by the email address
                  string userName = membershipService.GetUserNameByEmail(model.Email);

                  // confirm that the username is not null i.e. the username was found by email.
                  if(!string.IsNullOrEmpty(userName)) {

                           // Get the user by the userName
                           MembershipUser user = membershipService.GetUser(userName);

                           // if(user != null) {

                                    ..... execute the code as normal
                          }
                   }
         }
```

**Comment by kahanu** [comment]
@xnodeoncode - I'll check it, but in the meantime, what is the error you are seeing?

**Comment by xnodeoncode** [comment]
in the line:

string userName = membershipService.GetUserNameByEmail(model.Email);

if the email address is not in the database, then userName will be null. Well the very next line:

MembershipUser user = membershipService.GetUser(userName);

Errors with the message that "userName" cannot be null.

So I added a quick check to ensure that userName is not null which is what I included in the issue. We may also want to perform a model.Email.Trim() to ensure that whitespace isn't being passed through.

If you like, I can work on some of these trivial things with you. I think that the package is definitely a must have so good work. I'm just sharing some of the experiences that I'm having hopefully to make it even better.

I've also blogged about it in more detail at: www.bacardibryant.com.

**Comment by kahanu** [comment]
@xnodeoncode - nice catch.  I can get to this later today or this weekend.  I'm in the middle of moving.  :^)

**Comment by kahanu** [comment]
@xnodeoncode - nice blog.  I do plan on making SecurityGuard better, so I'm open to suggestions.  :^)  I also found out that with ASP.NET 4.5, the Membership system is using System.Web.Providers namespace instead of System.Web.Security.  This does change things a little but I'm not exactly sure what, since I think, the Providers namespace is still in Alpha.  I do want to look into that to maybe update newer versions of SecurityGuard to use those providers instead.  But testing and research will need to be done.

I also want to make it easier to modify the "theme" of the SecurityGuard Dashboard, so that they aren't affected with future updates.

These are all things on the TO DO list.  I just have to find time to do them.

**Comment by kahanu** [comment]
@xnodeoncode - ok, I've updated this bug.  I've also updated the NuGet package.
